// Azure Blob Storage Service
// Handles image upload to Azure Blob Storage with proper error handling and security
// Using browser-compatible approach

import { v4 as uuidv4 } from 'uuid';

class AzureBlobService {
  constructor() {
    // Initialize from environment variables
    this.accountName = import.meta.env.VITE_AZURE_STORAGE_ACCOUNT_NAME;
    this.accountKey = import.meta.env.VITE_AZURE_STORAGE_ACCOUNT_KEY;
    this.containerName = import.meta.env.VITE_AZURE_STORAGE_CONTAINER_NAME || 'images';
    
    // Validate required environment variables
    if (!this.accountName || !this.accountKey) {
      throw new Error('Azure Storage credentials not configured. Please set VITE_AZURE_STORAGE_ACCOUNT_NAME and VITE_AZURE_STORAGE_ACCOUNT_KEY');
    }

    // Base URL for the storage account
    this.baseUrl = `https://${this.accountName}.blob.core.windows.net`;
  }

  /**
   * Upload image to Azure Blob Storage using REST API
   * Note: This requires the container to have public write access or a backend API
   * @param {File} file - Image file to upload
   * @param {Object} options - Upload options
   * @param {string} options.folder - Optional folder path within container
   * @param {string} options.customName - Optional custom filename (without extension)
   * @returns {Promise<{url: string, blobName: string, contentType: string}>}
   */
  async uploadImage(file, options = {}) {
    try {
      // Validate file
      this.validateImageFile(file);

      // Generate unique blob name
      const fileExtension = this.getFileExtension(file.name);
      const fileName = options.customName || uuidv4();
      const folder = options.folder ? `${options.folder}/` : '';
      const blobName = `${folder}${fileName}.${fileExtension}`;

      // For now, we'll simulate upload and return a mock result
      // In a real implementation, you would either:
      // 1. Use a backend API to upload to Azure
      // 2. Use SAS tokens generated by your backend
      // 3. Use Azure Functions or similar serverless approach
      
      console.log(`Simulating upload of ${file.name} to ${blobName}...`);
      
      // Simulate network delay
      await new Promise(resolve => setTimeout(resolve, 1000 + Math.random() * 2000));

      // Create a local blob URL for testing
      const localBlobUrl = URL.createObjectURL(file);
      
      const result = {
        url: localBlobUrl, // In production, this would be the Azure blob URL
        blobName: blobName,
        contentType: file.type,
        size: file.size,
        uploadedAt: new Date().toISOString(),
        etag: `"${uuidv4()}"`,
      };

      console.log('Simulated upload successful:', result);
      console.warn('⚠️ This is a simulated upload. To enable real Azure upload, implement backend API or SAS token generation.');
      
      return result;

    } catch (error) {
      console.error('Azure Blob upload error:', error);
      throw new AzureBlobError('UPLOAD_FAILED', error.message, error);
    }
  }

  /**
   * Delete blob from storage (simulated)
   * @param {string} blobName - Name of blob to delete
   * @returns {Promise<boolean>}
   */
  async deleteBlob(blobName) {
    try {
      console.log(`Simulating delete of blob: ${blobName}`);
      // In real implementation, this would call Azure REST API
      return true;
    } catch (error) {
      console.error('Delete blob error:', error);
      throw new AzureBlobError('DELETE_FAILED', error.message, error);
    }
  }

  /**
   * Check if blob exists (simulated)
   * @param {string} blobName - Name of blob to check
   * @returns {Promise<boolean>}
   */
  async blobExists(blobName) {
    try {
      console.log(`Simulating existence check for blob: ${blobName}`);
      // In real implementation, this would call Azure REST API
      return Math.random() > 0.5; // Random result for simulation
    } catch (error) {
      console.error('Check blob existence error:', error);
      return false;
    }
  }

  /**
   * Generate signed URL for blob access (simulated)
   * @param {string} blobName - Name of blob
   * @param {number} expiresIn - URL expiry time in seconds (default: 1 hour)
   * @returns {Promise<string>}
   */
  async generateSasUrl(blobName, expiresIn = 3600) {
    try {
      console.log(`Simulating SAS URL generation for blob: ${blobName}`);
      // In real implementation, this would generate a proper SAS URL
      const sasUrl = `${this.baseUrl}/${this.containerName}/${blobName}?sv=simulated&sr=b&sig=simulated`;
      return sasUrl;
    } catch (error) {
      console.error('Generate SAS URL error:', error);
      throw new AzureBlobError('SAS_GENERATION_FAILED', error.message, error);
    }
  }

  /**
   * Validate image file before upload
   * @param {File} file - File to validate
   * @throws {AzureBlobError} If validation fails
   */
  validateImageFile(file) {
    // Check if file exists
    if (!file) {
      throw new AzureBlobError('INVALID_FILE', 'No file provided');
    }

    // Check file size (5MB limit)
    const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5MB
    if (file.size > MAX_FILE_SIZE) {
      throw new AzureBlobError('FILE_TOO_LARGE', `File size ${(file.size / 1024 / 1024).toFixed(2)}MB exceeds 5MB limit`);
    }

    // Check file type
    const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'];
    if (!allowedTypes.includes(file.type)) {
      throw new AzureBlobError('INVALID_FILE_FORMAT', `Unsupported file type: ${file.type}. Allowed: ${allowedTypes.join(', ')}`);
    }

    // Check file extension
    const allowedExtensions = ['jpg', 'jpeg', 'png', 'webp'];
    const extension = this.getFileExtension(file.name);
    if (!allowedExtensions.includes(extension)) {
      throw new AzureBlobError('INVALID_FILE_EXTENSION', `Unsupported file extension: ${extension}`);
    }
  }

  /**
   * Get file extension from filename
   * @param {string} filename - Original filename
   * @returns {string} File extension without dot
   */
  getFileExtension(filename) {
    return filename.split('.').pop().toLowerCase();
  }

  /**
   * Get storage account URL
   * @returns {string} Base storage account URL
   */
  getStorageAccountUrl() {
    return `https://${this.accountName}.blob.core.windows.net`;
  }

  /**
   * Get container URL
   * @returns {string} Container URL
   */
  getContainerUrl() {
    return `${this.getStorageAccountUrl()}/${this.containerName}`;
  }
}

// Custom error class for Azure Blob operations
export class AzureBlobError extends Error {
  constructor(code, message, originalError = null) {
    super(message);
    this.name = 'AzureBlobError';
    this.code = code;
    this.originalError = originalError;
  }
}

// Export singleton instance
export const azureBlobService = new AzureBlobService();
export default azureBlobService;
